const dataObject =[
    {"id":1,
    "name":"John",
    "age":"18",
        "position":"PM/PO",
        "created":"18/04/2020",
        "country":"Armenia",
        "city":"Erevan",
        "surname":"Smithsmithsmith",
        "salary":1000,
        "eduaction":"something here",
        "discription":"something looooooooooong heeeeeeeeeeeere",
        "discription2":"something "
    },
    {"id":2,
        "name":"Jane",
        "age":"22",
        "position":"UI/UX",
        "created":"21/06/2006",
        "country":"Armenia",
        "city":"Erevan",
        "surname":"Smith",
        "salary":1000,
        "eduaction":"something here",
        "discription":"something ",
        "discription2":"something looooooooooonger heeeeeeeeeeeere"

    },
    {"id":3,
        "name":"Alex",
        "age":"33",
        "position":"C#",
        "created":"03/08/2018",
        "country":"Armenia",
        "city":"Erevan",
        "surname":"Smith",
        "salary":1000,
        "eduaction":"something here",
        "discription":"something looooooooooong heeeeeeeeeeeere",
        "discription2":"something looooooooooonger heeeeeeeeeeeere"
    },
    {"id":4,
        "name":"John",
        "age":"18",
        "position":"PM/PO",
        "created":"18/04/2020",
        "country":"Armenia",
        "city":"Erevan",
        "surname":"Smith",
        "salary":1000,
        "eduaction":"something here",
        "discription":"something looooooooooong heeeeeeeeeeeere",
        "discription2":"something looooooooooonger heeeeeeeeeeeere"
    }
]
export default dataObject;